#!/bin/sh

# $CI_PROJECT_FILE_PATH is `/Volumes/workspace/repository/XcodeCloudSample.xcworkspace`
# In Xcoude Cloud, the file generated by SwfitGen was not read, and an error occurred with `not found`,
# If you create only the file in advance, the error does not occur
touch $CI_PROJECT_FILE_PATH/../XcodeCloudSamplePackage/Sources/XcodeCloudSamplePackage/Generated/StringsGenerated.swift
touch $CI_PROJECT_FILE_PATH/../XcodeCloudSamplePackage/Sources/XcodeCloudSamplePackage/Generated/CommonAssets.swift
